<a href="https://colab.research.google.com/github/caroccialberto/Python2026/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import random



0.10862134254965805

In [31]:
random.uniform(0, 1)

0.8969527603702883

In [16]:
n = 1000000
c = 0
r = 1.
for i in range(n):
  x = random.uniform(0,1.)
  y = random.uniform(0,1.)
  d = (x**2 + y**2)**0.5
  if d <= r:
    c += 1


In [17]:

P_a = c/n
a = P_a*r*2*2
pi = a*r**2

print(P_a)
print(pi)

0.785619
3.142476


In [68]:
def MC_pi(n = 10000, r = 1.):
  c = 0
  for i in range(n):
    x = random.uniform(0,r)
    y = random.uniform(0,r)
    d = (x**2 + y**2)**0.5
    if d <= r:
      c += 1
  P_a = c/n
  pi = P_a*4
  return P_a, pi

In [69]:
P_a, pi = MC_pi(n = 1000000, r = 3.)
print(P_a)
print(pi)

0.785073
3.140292


In [70]:
import math
math.pi

3.141592653589793

In [81]:
import numpy as np
a = np.array([1, 2, 3, 4], dtype = float)

In [75]:
a = range(1000)

%timeit [i**2 for i in a]

67.3 µs ± 1.21 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [74]:
b = np.arange(1000)
%timeit b**2

1.79 µs ± 353 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [78]:
c = np.array([[1, 2], [3, 4]])
c.ndim


2

In [82]:
print(c.shape)
print(b.shape)


(2, 2)
(1000,)


In [83]:
c = np.arange(27)
c.reshape((3, 3, 3))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [85]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [86]:
np.ones((2,1))

array([[1.],
       [1.]])

In [87]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [89]:
a = np.arange(10)

In [91]:
a[1]

np.int64(1)

In [92]:
a[-2]

np.int64(8)

In [93]:
a[0:3]

array([0, 1, 2])

In [94]:
a[::2]

array([0, 2, 4, 6, 8])

In [96]:
a = a.reshape(5,2)
a[3,1]

np.int64(7)

In [97]:
a[2,:]

array([4, 5])

In [98]:
a = np.arange(9)
b = a.reshape((3,3))

In [99]:
np.shares_memory(a,b)

True

In [100]:
a[3] = -1
print(b)

[[ 0  1  2]
 [-1  4  5]
 [ 6  7  8]]


In [101]:
b = a.copy()
np.shares_memory(a,b)

False

In [104]:
ene = np.random.exponential(size = 10, scale = 10)

In [107]:
print(ene)
print(ene[ene<3])
ene[ene<3] = 0
print(ene)

[ 2.20375803 11.64821359  5.04014018  0.70095135 12.32445263  3.53417749
  3.76528038 22.23399861  8.7400533  29.30008948]
[2.20375803 0.70095135]
[ 0.         11.64821359  5.04014018  0.         12.32445263  3.53417749
  3.76528038 22.23399861  8.7400533  29.30008948]


In [111]:
np.sin(math.pi/2)

np.float64(1.0)

In [4]:
import numpy as np

rng1 = np.random.default_rng(24)
rng2 = np.random.default_rng(42)
r = 1.
n = 100000000
x = rng1.uniform(low = 0., high = r, size = n)
y = rng2.uniform(low = 0., high = r, size = n)
d =  (x**2 + y**2)**.5
print(np.mean(d<=r)*4)


3.14172524
